// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT01CadastrarPerfilTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT01CadastrarPerfil() {
    driver.get("http://localhost:5173/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    assertThat(driver.findElement(By.linkText("Cadastre-se")).getText(), is("Cadastre-se"));
    driver.findElement(By.linkText("Cadastre-se")).click();
    assertThat(driver.findElement(By.cssSelector(".text-blue-900")).getText(), is("Cadastro"));
    assertThat(driver.findElement(By.cssSelector(".text-blue-400")).getText(), is("Preencha os campos abaixo"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".bg-sky-700"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".bg-sky-700")).getText(), is("Enviar"));
    driver.findElement(By.cssSelector(".bg-sky-700")).click();
    assertThat(driver.findElement(By.cssSelector(".flex:nth-child(1) > .input:nth-child(2) .text-xs > .text-red-500")).getText(), is("Informe um nome de usuário"));
    assertThat(driver.findElement(By.cssSelector(".flex:nth-child(3) > .input:nth-child(1) .text-xs > .text-red-500")).getText(), is("Informe uma senha"));
    assertThat(driver.findElement(By.cssSelector(".flex:nth-child(3) > .input:nth-child(2) .text-xs > .text-red-500")).getText(), is("Confirme a senha"));
    assertThat(driver.findElement(By.cssSelector(".flex:nth-child(1) > .input:nth-child(1) .text-xs > .text-red-500")).getText(), is("Informe nome e sobrenome"));
    driver.findElement(By.name("name")).sendKeys("ADONIAS PINHEIRO PIRES");
    {
      String value = driver.findElement(By.name("name")).getAttribute("value");
      assertThat(value, is("ADONIAS PINHEIRO PIRES"));
    }
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("adonias.pinheiro");
    driver.findElement(By.name("registration")).click();
    driver.findElement(By.name("registration")).sendKeys("200511140025");
    {
      String value = driver.findElement(By.name("registration")).getAttribute("value");
      assertThat(value, is("200511140025"));
    }
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("quase_4ever@yahoo.com.br");
    {
      String value = driver.findElement(By.name("email")).getAttribute("value");
      assertThat(value, is("quase_4ever@yahoo.com.br"));
    }
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Aa123456");
    driver.findElement(By.name("confirmationPassword")).click();
    driver.findElement(By.name("confirmationPassword")).sendKeys("Aa123456");
    driver.findElement(By.cssSelector(".text-teal-600 > .inline")).click();
    {
      String value = driver.findElement(By.name("password")).getAttribute("value");
      assertThat(value, is("Aa123456"));
    }
    driver.findElement(By.cssSelector(".bg-sky-700")).click();
    {
      String value = driver.findElement(By.name("geral.nome")).getAttribute("value");
      assertThat(value, is("ADONIAS PINHEIRO PIRES"));
    }
  }
}
